# Generated by Django 3.2.10 on 2022-03-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published', '-updated')},
        ),
    ]
